# Generated by Django 4.2.30 on 2026-06-02 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_templates", "0001_initial"),
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("to_address", models.EmailField(max_length=254)),
                ("from_address", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=998)),
                ("html_body", models.TextField(blank=True)),
                ("text_body", models.TextField(blank=True)),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("promotional", "Promotional"),
                        ],
                        default="transactional",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("permanently_failed", "Permanently Failed"),
                            ("suppressed", "Suppressed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("track_opens", models.BooleanField(default=True)),
                ("track_clicks", models.BooleanField(default=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="domains.domain",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="email_templates.templateversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="email_messa_user_id_d8938e_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="email_messa_status_3cae78_idx"
                    ),
                ],
            },
        ),
    ]
