# Generated by Django 4.2.30 on 2026-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("scheduled", "Scheduled"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("permanently_failed", "Permanently Failed"),
                    ("suppressed", "Suppressed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["status", "scheduled_at"], name="email_messa_status_aa6bd2_idx"
            ),
        ),
    ]
