# Generated by Django 4.2.30 on 2026-08-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("email_messages", "0002_message_scheduled_at_alter_message_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="bcc_addresses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="cc_addresses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(default="application/octet-stream", max_length=100),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="email_messages.message",
                    ),
                ),
            ],
        ),
    ]
