# Generated by Django 4.2.30 on 2026-06-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_sending_paused"),
        ("accounts", "0003_ipwhitelist_auditlog"),
    ]

    operations = []
