# Generated by Django 4.2.30 on 2026-05-29 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("spf_verified", models.BooleanField(default=False)),
                ("dkim_verified", models.BooleanField(default=False)),
                ("dmarc_verified", models.BooleanField(default=False)),
                ("dkim_private_key", models.TextField(blank=True, null=True)),
                ("dkim_public_key", models.TextField(blank=True, null=True)),
                ("dkim_selector", models.CharField(default="default", max_length=50)),
                ("verification_token", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "ordering": ["-created_at"],
                "unique_together": {("user", "domain")},
            },
        ),
    ]
