# Generated by Django 4.2.30 on 2026-08-27 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("domains", "0002_domain_dkim_rotation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[("exact", "One address"), ("wildcard", "Entire domain")],
                        default="wildcard",
                        max_length=10,
                    ),
                ),
                ("local_part", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_routes",
                        to="domains.domain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("domain", "local_part")},
            },
        ),
        migrations.CreateModel(
            name="InboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ses_message_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("from_address", models.EmailField(max_length=254)),
                ("to_address", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("text_body", models.TextField(blank=True)),
                ("html_body", models.TextField(blank=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("spam_verdict", models.CharField(blank=True, max_length=20)),
                ("virus_verdict", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("routed", "Routed"),
                            ("forwarded", "Forwarded"),
                            ("forward_failed", "Forward failed"),
                            ("unrouted", "Unrouted"),
                        ],
                        default="routed",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="inbound.inboundroute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="InboundAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="inbound_attachments/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(default="application/octet-stream", max_length=100),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="inbound.inboundmessage",
                    ),
                ),
            ],
        ),
    ]
