# Generated by Django 4.2.30 on 2026-06-04 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppressions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("bounce", "Bounce"),
                            ("complaint", "Complaint"),
                            ("unsubscribe", "Unsubscribe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "email"], name="suppression_user_id_a68d09_idx")
                ],
                "unique_together": {("user", "email")},
            },
        ),
    ]
