# Generated by Django 4.2.30 on 2026-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppressions", "0002_suppression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppression",
            name="reason",
            field=models.CharField(
                choices=[
                    ("bounce", "Bounce"),
                    ("complaint", "Complaint"),
                    ("unsubscribe", "Unsubscribe"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
    ]
