# Generated by Django 4.2.30 on 2026-06-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppressions", "0002_bounce_bounce_type"),
        ("suppressions", "0003_alter_suppression_reason"),
    ]

    operations = []
