# Generated by Django 4.2.30 on 2026-06-07 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("score", models.IntegerField(default=0)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("bounce_count", models.PositiveIntegerField(default=0)),
                ("complaint_count", models.PositiveIntegerField(default=0)),
                ("last_open", models.DateTimeField(blank=True, null=True)),
                ("last_click", models.DateTimeField(blank=True, null=True)),
                ("last_event", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "score"], name="analytics_c_user_id_f8788a_idx"),
                    models.Index(fields=["user", "email"], name="analytics_c_user_id_bd33b5_idx"),
                ],
                "unique_together": {("user", "email")},
            },
        ),
    ]
